# Generated by Django 5.0.6 on 2024-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
